FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y build-essential git cmake ninja-build gnuplot graphviz

# Get gRPC.
RUN git clone --depth 1 --recursive --shallow-submodules -b v1.47.3 https://github.com/grpc/grpc.git grpc_src

# Make `current` available.
RUN git clone --depth 1 -b stable_2022_04_10 https://github.com/c5t/current

# Build Debug gRPC.
RUN mkdir /grpc_build_debug
RUN (cd /grpc_build_debug; cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/grpc_installed_debug -DCMAKE_BUILD_TYPE=Debug /grpc_src)

RUN (cd /grpc_build_debug; make -j 20)  # NOTE(dkorolev): This `-j` argument can be tweaked, TODO(dkorolev): externally?
RUN (cd /grpc_build_debug; make install)

# Build Release gRPC.
RUN mkdir /grpc_build_release
RUN (cd /grpc_build_release; cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/grpc_installed_release -DCMAKE_BUILD_TYPE=Release /grpc_src)

RUN (cd /grpc_build_release; make -j 20)  # NOTE(dkorolev): This `-j` argument can be tweaked, TODO(dkorolev): externally?
RUN (cd /grpc_build_release; make install)

# TODO(dkorolev): Clean up these hacky scripts.
COPY CMakeLists.txt /
COPY Makefile /
COPY entrypoint.sh /
COPY lib/grpc_perftest.h /current/utils/
COPY lib/grpc_perftest_main.h /current/utils/

RUN mkdir /all_srcs
RUN chmod a+rwx /all_srcs

# TODO(dkorolev): Move this ugliness into `CMakeLists.txt`.
RUN echo "// Autogenerated, to have a dummy source file." >/all_srcs/___dummy___.cc
RUN echo "// Autogenerated, to have at least one \`.proto\` file. -- D.K.\\nsyntax = \"proto3\";" >/all_srcs/___dummy___.proto

ENTRYPOINT ["/entrypoint.sh"]
