name: Build Ubuntu Container

on:
  workflow_dispatch:

env:
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
      - name: docker build
        run: docker build .
      - name: docker push
        run: docker push "ghcr.io/$docker_username/grpcpp_exrperiment:${GIT_COMMIT::8}-ubuntu"
