name: Build and Publish

on:
  workflow_dispatch:

env:
  SHA: ${{ github.sha }}

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: qemu
        uses: docker/setup-qemu-action@v1

      - name: dockerx setup
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        run: echo "${{ secrets.DOCKERHUB_CRNT_PASSWORD }}" | docker login -u crnt --password-stdin

      - name: build and push
        run: docker buildx build --push --tag docker.io/crnt/grpcpp:${SHA::6} --platform linux/amd64,linux/arm64/v8 .

      - name: build and push latest
        run: docker buildx build --push --tag docker.io/crnt/grpcpp:latest --platform linux/amd64,linux/arm64/v8 .
