name: Build and Publish

on:
  workflow_dispatch:

env:
  SHA: ${{ github.sha }}

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_CRNT_PASSWORD }}" | docker login -u crnt --password-stdin

      - name: Docker Build
        run: docker build -t crnt/grpcpp:${SHA::6} .

      - name: docker push
        run: docker push crnt/grpcpp:${SHA::6}
